<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Report;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class ReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api');
    }

    public function index(): JsonResponse
    {
        $user = auth('api')->user();
        $reports = Report::whereIn('company_id', $user->companies()->pluck('id'))
            ->paginate(15);

        return response()->json($reports);
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'company_id' => 'required|exists:companies,id',
            'report_type' => 'required|string',
            'filters' => 'sometimes|array',
        ]);

        $report = Report::create([
            ...$validated,
            'generated_by' => auth('api')->user()->id,
            'download_url' => null, // Would be generated by a job/service
        ]);

        return response()->json([
            'message' => 'Report created successfully',
            'report' => $report,
        ], 201);
    }

    public function show(Report $report): JsonResponse
    {
        return response()->json($report);
    }

    public function destroy(Report $report): JsonResponse
    {
        $report->delete();
        return response()->json(['message' => 'Report deleted successfully']);
    }
}
